apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: asia-northeast1-docker.pkg.dev/kzs-sandbox/public/backend-grpc:v1
          imagePullPolicy: Always
          name: backend
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: KIND
              value: "Backend-grpc"
            - name: VERSION
              value: "v1"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: test
spec:
  ports:
    - port: 8080
      name: backend-grpc
      protocol: TCP
  selector:
    app: backend
  type: ClusterIP
---