apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: asia-northeast1-docker.pkg.dev/kzs-sandbox/public/frontend-rest:v1
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: KIND
              value: "Frontend-rest"
            - name: VERSION
              value: "v1"
            - name: BE
              value: "backend.test.svc.cluster.local"
            - name: BE_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: test
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: test
spec:
  defaultBackend:
    service:
      name: frontend
      port:
        number: 8080
